#ifndef __HI_TEE_ERRCODE_H__
#define __HI_TEE_ERRCODE_H__

#include "hi_type.h"
/********************************Error Code Definition********************************/
/** \addtogroup      TEE */
/** @{ */  /** <!-- [TEE] */

#define HI_TEE_ERRCODE_DEF(moduleid, errid)     (HI_S32)(0x80000000 | ((moduleid) << 16)  | (errid))

/**< Operation Error Define */
#define HI_TEE_ERR_DEVICE                       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0001)    /**< Device Operation Error */
#define HI_TEE_ERR_MEM                          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0002)    /**< Memory Operation Error */
#define HI_TEE_ERR_SEM                          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0003)    /**< Semaphore Operation Error */
#define HI_TEE_ERR_TIMER                        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0004)    /**< Timer Operation error */
#define HI_TEE_ERR_DATABASE                     HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0005)    /**< Database Operation Error */
#define HI_TEE_ERR_THREAD                       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0006)    /**< Thread Operation Error */
#define HI_TEE_ERR_FILE                         HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0007)    /**< File Operation Error */
#define HI_TEE_ERR_FLASH                        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0008)    /**< Flash Operation Error*/
#define HI_TEE_ERR_CHANNEL                      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x0009)    /**< Channel Operation Error*/
#define HI_TEE_ERR_LOCK                         HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x000A)    /**< Lock Operation Error */
#define HI_TEE_ERR_IOCTRL                       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x000B)    /**< IO Operation Error */
#define HI_TEE_ERR_ENCRYPT                      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x000C)    /**< Encrypt Operation Error */
#define HI_TEE_ERR_DECRYPT                      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x000D)    /**< Decrypt Operation Error */
#define HI_TEE_ERR_VERIFY                       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x000E)    /**< Verify Operation Error */

/**< Status Error Define */
#define HI_TEE_ERR_STATUS                       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1001)    /**< Status Error */
#define HI_TEE_ERR_TIMEOUT                      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1002)    /**< Time Out Error */
#define HI_TEE_ERR_INUSE                        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1003)    /**< In use(Something is Busy) */
#define HI_TEE_ERR_EXIST                        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1004)    /**< Already exists */
#define HI_TEE_ERR_NOEXIST                      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1005)    /**< Non-existent */
#define HI_TEE_ERR_INITED                       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1006)    /**< Already initialized */
#define HI_TEE_ERR_UNINITED                     HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1007)    /**< Not initialized */
#define HI_TEE_ERR_UNSUPPORTED                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1008)    /**< Unsupported */
#define HI_TEE_ERR_UNAVAILABLE                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x1009)    /**< Unavailable */
#define HI_TEE_ERR_OVERFLOW                     HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x100A)    /**< Overflow */
#define HI_TEE_ERR_NOPERMISSION                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x100B)    /**< Have no authority */
#define HI_TEE_ERR_NORESOURCES                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x100C)    /**< Lack of resources */

/**< Other Error Define */
#define HI_TEE_ERR_ILLEGAL_IMAGE                HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2001)    /**< Illegal Image */
#define HI_TEE_ERR_ILLEGAL_UUID                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2002)    /**< Illegal UUID */
#define HI_TEE_ERR_ILLEGAL_KEY                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2003)    /**< Illegal KEY */
#define HI_TEE_ERR_ILLEGAL_PID                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2004)    /**< Illegal PID */
#define HI_TEE_ERR_ILLEGAL_VERSION              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2005)    /**< Illegal Version */
#define HI_TEE_ERR_INVALID_HANDLE               HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2006)    /**< Invalid Handle */
#define HI_TEE_ERR_INVALID_PTR                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2007)    /**< Invalid Pointer */
#define HI_TEE_ERR_INVALID_PARAM                HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2008)    /**< Invalid Parameter */
#define HI_TEE_ERR_INVALID_ADDR                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x2009)    /**< Invalid Address */
#define HI_TEE_ERR_INVALID_LENGTH               HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x200A)    /**< Invalid Length */
#define HI_TEE_ERR_EXTERNAL                     HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x200B)    /**< External Error */
#define HI_TEE_ERR_UNKNOWNED                    HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x200C)    /**< Unknown Error */
#define HI_TEE_ERR_INVALID_TAID                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_LOG, 0x200D)    /**< INVALID TAID */

/**< Module Error Define */
#define HI_ERR_DMX_INVALID_PARA                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0002)
#define HI_ERR_DMX_NOT_SUPPORT                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0004)
#define HI_ERR_DMX_UNMATCH_CHAN                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x000b)
#define HI_ERR_DMX_NOATTACH_KEY                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0013)
#define HI_ERR_DMX_UNMATCH_KEY                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0014)
#define HI_ERR_DMX_NOFREE_KEY                   HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0015)
#define HI_ERR_DMX_ATTACHED_KEY                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0016)
#define HI_ERR_DMX_OCCUPIED_PID                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0020)
#define HI_ERR_DMX_BUSY_CHAN                    HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0037)
#define HI_ERR_DMX_BUSY_KEY                     HI_TEE_ERRCODE_DEF(HI_MODULE_ID_DEMUX, 0x0039)

#define HI_TEE_ERR_CIPHER_INVALID_HANDLE        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0001)
#define HI_TEE_ERR_CIPHER_FAILED_CONFIGAES      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0002)
#define HI_TEE_ERR_CIPHER_FAILED_CONFIGDES      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0003)
#define HI_TEE_ERR_CIPHER_NO_AVAILABLE_RNG      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0004)
#define HI_TEE_ERR_CIPHER_REGISTER_IRQ          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0005)
#define HI_TEE_ERR_CIPHER_ILLEGAL_DATA          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0006)
#define HI_TEE_ERR_CIPHER_RSA_SIGN              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0007)
#define HI_TEE_ERR_CIPHER_RSA_VERIFY            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_CIPHER, 0x0008)

#define HI_ERR_KLAD_NOT_INIT                    HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0001)
#define HI_ERR_KLAD_NULL_PTR                    HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0002)
#define HI_ERR_KLAD_INVALID_HANDLE              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0003)
#define HI_ERR_KLAD_INVALID_ALG                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0004)
#define HI_ERR_KLAD_INVALID_TARGET              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0005)
#define HI_ERR_KLAD_INVALID_TARGETADDR          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0006)
#define HI_ERR_KLAD_NO_MEMORY                   HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0007)
#define HI_ERR_KLAD_WAIT_TIMEOUT                HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0008)
#define HI_ERR_KLAD_NOT_FINDKLAD                HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0009)
#define HI_ERR_KLAD_NOT_FINDSESSION             HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x000a)
#define HI_ERR_KLAD_NOT_SETATTR                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x000b)
#define HI_ERR_KLAD_NOT_FINDCALLBACK            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x000c)
#define HI_ERR_KLAD_KEY_NOT_READDY              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x000d)
#define HI_ERR_KLAD_ALREADY_SETATTR             HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x000e)
#define HI_ERR_KLAD_NOT_SET_SESSIONKEY          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x000f)
#define HI_ERR_KLAD_NOT_SET_CONTENTKEY          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0010)
#define HI_ERR_KLAD_ALREADY_SETTARGET           HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0011)
#define HI_ERR_KLAD_NOT_SETTARGET               HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0012)
#define HI_ERR_KLAD_DETACH_ERRTARGET            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0013)
#define HI_ERR_KLAD_INVALID_LEVEL               HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0014)
#define HI_ERR_KLAD_UNAVAILABLE_TARGET          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0015)
#define HI_ERR_KLAD_FAILED_SETIV                HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0016)
#define HI_ERR_KLAD_CHECK_BASE                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0017)
#define HI_ERR_KLAD_CHECK_OTP_CONFIG_DISABLE    HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0018)
#define HI_ERR_KLAD_CHECK_LEVEL                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0019)
#define HI_ERR_KLAD_CHECK_DSC_MODE              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x001a)
#define HI_ERR_KLAD_CHECK_PORT                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x001b)
#define HI_ERR_KLAD_CHECK_ROOTKEY_NOT_READY     HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x001c)
#define HI_ERR_KLAD_CHECK_LEVEL1_NOT_READY      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x001d)
#define HI_ERR_KLAD_CHECK_LEVEL2_NOT_READY      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x001e)
#define HI_ERR_KLAD_CHECK_LEVEL3_NOT_READY      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x001f)
#define HI_ERR_KLAD_CHECK_LEVEL4_NOT_READY      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0020)
#define HI_ERR_KLAD_CHECK_LEVEL5_NOT_READY      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0021)
#define HI_ERR_KLAD_CHECK_DCAS_PROFILE          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0022)
#define HI_ERR_KLAD_CHECK_TDES_KEY              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0023)
#define HI_ERR_KLAD_CHECK_C2_TA_HASH            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0024)
#define HI_ERR_KLAD_CHECK_CLEAR_CW_CONFIG       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0025)
#define HI_ERR_KLAD_CHECK_CW                    HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0026)
#define HI_ERR_KLAD_CHECK_TEE_ENABLE            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0027)
#define HI_ERR_KLAD_INVALID_ENGINE              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0028)
#define HI_ERR_KLAD_INVALID_EVENORODD           HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0029)
#define HI_ERR_KLAD_NOT_SUPPORT                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x002a)
#define HI_ERR_KLAD_INVALID_IVLENGTH            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x002b)
#define HI_ERR_KLAD_NORESOURCE                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x002c)
#define HI_ERR_KLAD_UNKNOWN_CMD                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x002d)
#define HI_ERR_KLAD_UUID_FAIL                   HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x002e)
#define HI_ERR_KLAD_CERT_UNEXPECTED_STA         HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0100)
#define HI_ERR_KLAD_CERT_UNEXPECTED_EMI         HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0101)
#define HI_ERR_KLAD_CERT_INVALID_KEY            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0102)
#define HI_ERR_KLAD_CERT_FAILED_LOCKED          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0103)
#define HI_ERR_KLAD_CERT_FAILED_UNLOCKED        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0104)
#define HI_ERR_KLAD_CERT_UNEXPECTED_CW          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0105)
#define HI_ERR_KLAD_CERT_FAILED_MUTEX           HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0106)
#define HI_ERR_KLAD_CERT_FAILED_LOCK_STA        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0107)
#define HI_ERR_KLAD_CERT_ERR_ALG                HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0108)
#define HI_ERR_KLAD_CERT_ERR_PRT_SEL            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0109)
#define HI_ERR_KLAD_CERT_ERR_USAGE              HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x010a)
#define HI_ERR_KLAD_CERT_COMMAND_TIMEOUT        HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x010b)
#define HI_ERR_KLAD_CERT_FAILED_AUTHORITY       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x010c)
#define HI_ERR_KLAD_CERT_SENDDONE_TIMEOUT       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x010d)
#define HI_ERR_KLAD_CERT_SENDCTRL_TIMEOUT       HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x010e)
#define HI_ERR_KLAD_CERT_UNKNOWN_CMD            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x010f)
#define HI_ERR_KLAD_CERT_ERR                    HI_TEE_ERRCODE_DEF(HI_MODULE_ID_KLAD, 0x0110)

#define HI_ERR_OTP_NULL_PTR                     HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0001)
#define HI_ERR_OTP_INVALID_ADDR                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0002)
#define HI_ERR_OTP_INVALID_KEYLEN               HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0003)
#define HI_ERR_OTP_INVALID_CHIPIDLEN            HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0004)
#define HI_ERR_OTP_INVALID_PARAM                HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0005)
#define HI_ERR_OTP_VERSION_FULL                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0006)
#define HI_ERR_OTP_NOT_INITRDY                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0007)
#define HI_ERR_OTP_FAIL_PRMRD                   HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0008)
#define HI_ERR_OTP_FAIL_RD                      HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0009)
#define HI_ERR_OTP_DISABLE_PROG                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x000a)
#define HI_ERR_OTP_FULL_VERSION                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x000b)
#define HI_ERR_OTP_FAILED_CHECKVERSION          HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x000c)
#define HI_ERR_OTP_FAILED_AUTH                  HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x000d)
#define HI_ERR_OTP_TAID_SETED                   HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x000f)
#define HI_ERR_OTP_INVALID_TAID                 HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0010)
#define HI_ERR_OTP_DUPLICATE_TAID               HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0011)
#define HI_ERR_OTP_NO_AVAILABLE_INDEX           HI_TEE_ERRCODE_DEF(HI_MODULE_ID_OTP, 0x0012)
/** @} */  /** <!-- ====End of Error Code Definition==== */
#endif

