
obj-$(CONFIG_TIMER_HISP804)		+= hisp804-timer.o
obj-$(CONFIG_TIMER_HIFIXTIMER)		+= hifixtimer.o
obj-$(CONFIG_MTD_BLOCK_ROMBLOCK)	+= romblock.o
obj-y					+= export_sym.o
obj-$(CONFIG_PART_CHANGE)		+= part-change.o
obj-$(CONFIG_HI_I2C)			+= i2c-hisi.o
obj-$(CONFIG_ARCH_HI3798MV2X)		+= ddr_watchpoint.o ddr_watchzone.o
obj-$(CONFIG_ARCH_HI3796MV2X)		+= ddr_watchpoint.o ddr_watchzone.o
obj-$(CONFIG_HAVE_HW_BREAKPOINT)	+= hw_breakpoint.o
obj-m                                   += hrtimer_test.o
