LOCAL_C_INCLUDES := \
    -I$(HI_TEE_DRV_DIR)/include \
    -I$(HI_TEE_API_DIR)/pvr

LOCAL_SRC_FILES := \
         hisi_pvr_task.o

LOCAL_MODULE:= $(OUT)/task_hisi_pvr.elf

include $(HI_TEE_TA_DIR)/ta.mak