#ADD PLATFORM MACRO HERE
ifeq ($(strip $(CFG_HI_TEE_HI3798CV2X_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_HI3798CV2X_SUPPORT
endif

ifeq ($(strip $(CFG_HI_TEE_HI3798MX_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCFG_HI_TEE_HI3798MX_SUPPORT
endif

TRUSTEDCORE_DEVCHIP_CFLAGS += -fno-short-enums -fstack-protector-all -Wstack-protector -ffreestanding

ifeq ($(strip $(CFG_HI_TEE_WERROR_SUPPORT)), y)
TRUSTEDCORE_DEVCHIP_CFLAGS += -Werror -Wall
endif

TRUSTEDCORE_DEVCHIP_CFLAGS += -DCHIP_TYPE_$(HI_CHIP_TYPE)

TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_DEVCHIP_LOG_LEVEL=$(TRUSTEDCORE_DEVCHIP_LOG_LEVEL)

ifeq ($(WITH_NEON_SUPPORT) , true)
TRUSTEDCORE_DEVCHIP_CFLAGS += -mfloat-abi=softfp -mfpu=neon
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCONFIG_NEON_SUPPORT
endif

include $(TRUSTEDCORE_DIR)/platform/${PLATFORM_DIR}/${PLATFORM_DIR_NAME}/module_list.mak

ifeq ($(strip $(WITH_CLEAR_BOOT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DWITH_CLEAR_BOOT
endif

ifeq ($(strip $(WITH_ARMV8_SUPPORT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DWITH_ARMV8_SUPPORT
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DATF_MEM_SIZE=$(ATF_MEM_SIZE)
endif

ifeq ($(strip $(TRUSTEDCORE_LARGER_MEM)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTRUSTEDCORE_LARGER_MEM
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTRUSTEDCORE_SHAREMEM_SIZE=$(TRUSTEDCORE_SHAREMEM_SIZE)
endif

ifeq ($(strip $(WITH_TUI_SUPPORT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTEE_SUPPORT_TUI
endif

ifeq ($(strip $(TRUSTEDCORE_FINGERPRINT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTEE_FINGERPRINT
endif

TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_RAM_TOTAL_AMOUNT=$(TRUSTEDCORE_RAM_TOTAL_AMOUNT)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_RAM_ORDER=$(TRUSTEDCORE_RAM_ORDER)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_SEC_MMZ_MEM_SIZE=$(TRUSTEDCORE_SEC_MMZ_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE=$(TRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_TA_RUN_MEM_SIZE=$(TRUSTEDCORE_TA_RUN_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_TA_SHARE_MEM_SIZE=$(TRUSTEDCORE_TA_SHARE_MEM_SIZE)

ifeq ($(strip $(WITH_GP_V1_1_SUPPORTED)), true)
$(info --- GP_V1_1_SUPPORTED ---)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DGP_V1_1_SUPPORTED
endif

TRUSTEDCORE_DEVCHIP_ASFLAGS += $(TRUSTEDCORE_DEVCHIP_CFLAGS)

$(info TRUSTEDCORE_DEVCHIP_CFLAGS=$(TRUSTEDCORE_DEVCHIP_CFLAGS))

#################################################
# packing config
#################################################
ifeq ($(strip $(CONFIG_TRUSTEDCORE_RELEASE)), true)
PACKIMG_DEBUG_FLAG = 0
else
PACKIMG_DEBUG_FLAG = 1
endif
# Create TA list for pack image
TASK_HISI_LIST :=
IMG_PATH = $(OUT)
ifeq ($(strip $(CFG_HI_TEE_SEC_MMZ_SUPPORT)), y)
	TASK_SEC_MMZ_NAME = task_sec_mmz
	TASK_SEC_MMZ_UUID = d93d4688bde711e6a4a6cec0c932ce01
	TASK_SEC_MMZ_PATH = ${IMG_PATH}/${TASK_SEC_MMZ_NAME}.elf
	TASK_SEC_MMZ_CFG = ${TASK_SEC_MMZ_PATH},${TASK_SEC_MMZ_NAME},${TASK_SEC_MMZ_UUID},0x1000
	TASK_HISI_LIST += ${TASK_SEC_MMZ_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_VFMW_SUPPORT)), y)
	TASK_HISI_VFMW_NAME = vfmw_task
	TASK_HISI_VFMW_UUID = 3c2bfc84c03c11e6a4a6cec0c932ce01
	TASK_HISI_VFMW_PATH = ${IMG_PATH}/${TASK_HISI_VFMW_NAME}.elf
	TASK_HISI_VFMW_CFG = ${TASK_HISI_VFMW_PATH},${TASK_HISI_VFMW_NAME},${TASK_HISI_VFMW_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HISI_VFMW_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_SMMU_SUPPORT)), y)
	TASK_SMMU_NAME = smmu_task
	TASK_SMMU_UUID = 08684bd8bde811e6a4a6cec0c932ce01
	TASK_SMMU_PATH = ${IMG_PATH}/${TASK_SMMU_NAME}.elf
	TASK_SMMU_CFG = ${TASK_SMMU_PATH},${TASK_SMMU_NAME},${TASK_SMMU_UUID},0x1000
	TASK_HISI_LIST += ${TASK_SMMU_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_TEST_SUPPORT)), y)
	TASK_HISI_TEST_NAME = task_hisi_test
	TASK_HISI_TEST_UUID = 0E0E0E0E0E0E0E0E0E0E0E0E0E0E0E0E
	TASK_HISI_TEST_PATH = ${IMG_PATH}/${TASK_HISI_TEST_NAME}.elf
	TASK_HISI_TEST_CFG = ${TASK_HISI_TEST_PATH},${TASK_HISI_TEST_NAME},${TASK_HISI_TEST_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HISI_TEST_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_DEMUX_SUPPORT)), y)
	TASK_DMX_NAME = task_hisi_dmx
	TASK_DMX_UUID = ca0b4c78bcf211e6a4a6cec0c932ce01
	TASK_DMX_PATH = ${IMG_PATH}/${TASK_DMX_NAME}.elf
	TASK_DMX_CFG = ${TASK_DMX_PATH},${TASK_DMX_NAME},${TASK_DMX_UUID},0x1000
	TASK_HISI_LIST += ${TASK_DMX_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_PLCIPHER_SUPPORT)), y)
	TASK_PLCIPHER_NAME = task_hisi_plcipher
	TASK_PLCIPHER_UUID = 7ce373d960f743aaa73f4e6bc985996b
	TASK_PLCIPHER_PATH = ${IMG_PATH}/${TASK_PLCIPHER_NAME}.elf
	TASK_PLCIPHER_CFG = ${TASK_PLCIPHER_PATH},${TASK_PLCIPHER_NAME},${TASK_PLCIPHER_UUID},0x1000
	TASK_HISI_LIST += ${TASK_PLCIPHER_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_CRYPTOEN_SUPPORT)), y)
	TASK_NOCS_NAME = task_hisi_cryptoen
	TASK_NOCS_UUID = d9420c8e8daa439da1e2913016b1810c
	TASK_NOCS_PATH = ${IMG_PATH}/${TASK_NOCS_NAME}.elf
	TASK_NOCS_CFG = ${TASK_NOCS_PATH},${TASK_NOCS_NAME},${TASK_NOCS_UUID},0x1000
	TASK_HISI_LIST += ${TASK_NOCS_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_PVR_SUPPORT)), y)
	TASK_HISI_PVR_NAME = task_hisi_pvr
	TASK_HISI_PVR_UUID = 569985febac011e6a4a6cec0c932ce01
	TASK_HISI_PVR_PATH = ${IMG_PATH}/${TASK_HISI_PVR_NAME}.elf
	TASK_PVR_CFG = ${TASK_HISI_PVR_PATH},${TASK_HISI_PVR_NAME},${TASK_HISI_PVR_UUID},0x1000
	TASK_HISI_LIST += ${TASK_PVR_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_HDMI_SUPPORT)), y)
	TASK_HDMI_NAME = task_sec_hdmi
	TASK_HDMI_UUID = 40e4a246c1a711e6a4a6cec0c932ce01
	TASK_HDMI_PATH = ${IMG_PATH}/${TASK_HDMI_NAME}.elf
	TASK_HDMI_CFG = ${TASK_HDMI_PATH},${TASK_HDMI_NAME},${TASK_HDMI_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HDMI_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_WIDEVINE_SUPPORT)), y)
	TASK_WIDEVINE_NAME = task_wv_server
	TASK_WIDEVINE_UUID = 79b7778897894a7aa2beb60155eef5f8
	TASK_WIDEVINE_PATH = ${IMG_PATH}/${TASK_WIDEVINE_NAME}.elf
	TASK_WIDEVINE_CFG = ${TASK_WIDEVINE_PATH},${TASK_WIDEVINE_NAME},${TASK_WIDEVINE_UUID},0x1000
	TASK_WIDEVINE_RELEASE_PATH = $(TRUSTEDCORE_RELEASE_DIR)/$(HI_CHIP_TYPE)/$(CFG_HI_TVP_MEM_LAYOUT)/${TASK_WIDEVINE_NAME}.elf
ifneq ($(strip $(CFG_HI_TEE_TA_LOAD_SUPPORT)), y)
ifeq ($(strip $(CONFIG_TRUSTEDCORE_RELEASE)), )
	TASK_HISI_LIST += ${TASK_WIDEVINE_CFG}
else
ifeq ($(TASK_WIDEVINE_RELEASE_PATH), $(wildcard $(TASK_WIDEVINE_RELEASE_PATH)))
	TASK_HISI_LIST += ${TASK_WIDEVINE_CFG}
endif
endif
endif
endif

ifeq ($(strip $(CFG_HI_TEE_VDP_VERIMATRIX_SUPPORT)), y)
	TASK_HISI_VDP_NAME = task_hisi_vdp
	TASK_HISI_VDP_UUID = 1E1E1E1E1E1E1E1E1E1E1E1E1E1E1E1E
	TASK_HISI_VDP_PATH = ${IMG_PATH}/${TASK_HISI_VDP_NAME}.elf
	TASK_HISI_VDP_CFG = ${TASK_HISI_VDP_PATH},${TASK_HISI_VDP_NAME},${TASK_HISI_VDP_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HISI_VDP_CFG}
endif


ifeq ($(strip $(CFG_HI_TEE_EMPTYDRM_SUPPORT)), y)
	TASK_EMPTYDRM_NAME = task_emptydrm
	TASK_EMPTYDRM_UUID = 79b7778897894a7aa2beb60155111111
	TASK_EMPTYDRM_PATH = ${IMG_PATH}/${TASK_EMPTYDRM_NAME}.elf
	TASK_EMPTYDRM_CFG = ${TASK_EMPTYDRM_PATH},${TASK_EMPTYDRM_NAME},${TASK_EMPTYDRM_UUID},0x1000
	TASK_HISI_LIST += ${TASK_EMPTYDRM_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_PLAYREADY_SUPPORT)), y)
	TASK_PLAYREADY_NAME = task_playready
	TASK_PLAYREADY_UUID = 79b7778897894a7aa2beb60155eef5f9
	TASK_PLAYREADY_PATH = ${IMG_PATH}/${TASK_PLAYREADY_NAME}.elf
	TASK_PLAYREADY_CFG = ${TASK_PLAYREADY_PATH},${TASK_PLAYREADY_NAME},${TASK_PLAYREADY_UUID},0x1000
	TASK_PLAYREADY_RELEASE_PATH = $(TRUSTEDCORE_RELEASE_DIR)/$(HI_CHIP_TYPE)/$(CFG_HI_TVP_MEM_LAYOUT)/${TASK_PLAYREADY_NAME}.elf
ifneq ($(strip $(CFG_HI_TEE_TA_LOAD_SUPPORT)), y)
ifeq ($(strip $(CONFIG_TRUSTEDCORE_RELEASE)), )
	TASK_HISI_LIST += ${TASK_PLAYREADY_CFG}
else
ifeq ($(TASK_PLAYREADY_RELEASE_PATH), $(wildcard $(TASK_PLAYREADY_RELEASE_PATH)))
	TASK_HISI_LIST += ${TASK_PLAYREADY_CFG}
endif
endif
endif
endif

ifeq ($(strip $(CFG_HI_TEE_DEMO_SUPPORT)), y)
	TASK_HISI_DEMO_NAME = task_hisi_demo
	TASK_HISI_DEMO_UUID = 8f194022c9a211e69d9dcec0c932ce01
	TASK_HISI_DEMO_PATH = ${IMG_PATH}/${TASK_HISI_DEMO_NAME}.elf
	TASK_HISI_DEMO_CFG = ${TASK_HISI_DEMO_PATH},${TASK_HISI_DEMO_NAME},${TASK_HISI_DEMO_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HISI_DEMO_CFG}
endif



ifeq ($(strip $(CFG_HI_TEE_VMXTAC_TEST_SUPPORT)), y)
	TASK_STB_VMX_ULTRA_VMXTA_NAME = VMXTA
	TASK_STB_VMX_ULTRA_VMXTA_UUID = d70f330cc8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_VMXTA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_VMXTA_NAME}.elf
	TASK_VMX_ULTRA_VMXTA_CFG = ${TASK_STB_VMX_ULTRA_VMXTA_PATH},${TASK_STB_VMX_ULTRA_VMXTA_NAME},${TASK_STB_VMX_ULTRA_VMXTA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_VMXTA_CFG}

	TASK_STB_VMX_ULTRA_VIDEOMARKTA_NAME = videomarkTA
	TASK_STB_VMX_ULTRA_VIDEOMARKTA_UUID = d70f3550c8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_VIDEOMARKTA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_VIDEOMARKTA_NAME}.elf
	TASK_VMX_ULTRA_VIDEOMARKTA_CFG = ${TASK_STB_VMX_ULTRA_VIDEOMARKTA_PATH},${TASK_STB_VMX_ULTRA_VIDEOMARKTA_NAME},${TASK_STB_VMX_ULTRA_VIDEOMARKTA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_VIDEOMARKTA_CFG}

	TASK_STB_VMX_ULTRA_CLIENTID2TA_NAME = vmxId2TA
	TASK_STB_VMX_ULTRA_CLIENTID2TA_UUID = d70f364ac8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_CLIENTID2TA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_CLIENTID2TA_NAME}.elf
	TASK_VMX_ULTRA_CLIENTID2TA_CFG = ${TASK_STB_VMX_ULTRA_CLIENTID2TA_PATH},${TASK_STB_VMX_ULTRA_CLIENTID2TA_NAME},${TASK_STB_VMX_ULTRA_CLIENTID2TA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_CLIENTID2TA_CFG}

	TASK_STB_VMX_ULTRA_CLIENTID3TA_NAME = vmxId3TA
	TASK_STB_VMX_ULTRA_CLIENTID3TA_UUID = d70f3726c8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_CLIENTID3TA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_CLIENTID3TA_NAME}.elf
	TASK_VMX_ULTRA_CLIENTID3TA_CFG = ${TASK_STB_VMX_ULTRA_CLIENTID3TA_PATH},${TASK_STB_VMX_ULTRA_CLIENTID3TA_NAME},${TASK_STB_VMX_ULTRA_CLIENTID3TA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_CLIENTID3TA_CFG}
else
    ifeq ($(strip $(CFG_HI_TEE_VMX_ULTRA_SUPPORT)), y)
	TASK_STB_VMX_ULTRA_VMXTA_NAME = VMXTA
	TASK_STB_VMX_ULTRA_VMXTA_UUID = d70f330cc8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_VMXTA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_VMXTA_NAME}.elf
	TASK_VMX_ULTRA_VMXTA_CFG = ${TASK_STB_VMX_ULTRA_VMXTA_PATH},${TASK_STB_VMX_ULTRA_VMXTA_NAME},${TASK_STB_VMX_ULTRA_VMXTA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_VMXTA_CFG}

	TASK_STB_VMX_ULTRA_VIDEOMARKTA_NAME = videomarkTA
	TASK_STB_VMX_ULTRA_VIDEOMARKTA_UUID = d70f3550c8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_VIDEOMARKTA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_VIDEOMARKTA_NAME}.elf
	TASK_VMX_ULTRA_VIDEOMARKTA_CFG = ${TASK_STB_VMX_ULTRA_VIDEOMARKTA_PATH},${TASK_STB_VMX_ULTRA_VIDEOMARKTA_NAME},${TASK_STB_VMX_ULTRA_VIDEOMARKTA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_VIDEOMARKTA_CFG}

	TASK_STB_VMX_ULTRA_CLIENTID2TA_NAME = vmxId2TA
	TASK_STB_VMX_ULTRA_CLIENTID2TA_UUID = d70f364ac8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_CLIENTID2TA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_CLIENTID2TA_NAME}.elf
	TASK_VMX_ULTRA_CLIENTID2TA_CFG = ${TASK_STB_VMX_ULTRA_CLIENTID2TA_PATH},${TASK_STB_VMX_ULTRA_CLIENTID2TA_NAME},${TASK_STB_VMX_ULTRA_CLIENTID2TA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_CLIENTID2TA_CFG}

	TASK_STB_VMX_ULTRA_CLIENTID3TA_NAME = vmxId3TA
	TASK_STB_VMX_ULTRA_CLIENTID3TA_UUID = d70f3726c8dd11e69d9dcec0c932ce01
	TASK_STB_VMX_ULTRA_CLIENTID3TA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_CLIENTID3TA_NAME}.elf
	TASK_VMX_ULTRA_CLIENTID3TA_CFG = ${TASK_STB_VMX_ULTRA_CLIENTID3TA_PATH},${TASK_STB_VMX_ULTRA_CLIENTID3TA_NAME},${TASK_STB_VMX_ULTRA_CLIENTID3TA_UUID},0x1000
	TASK_HISI_LIST += ${TASK_VMX_ULTRA_CLIENTID3TA_CFG}

	TASK_STB_VMX_ULTRA_CLIENTID1TA_NAME = vmxId1TA
        TASK_STB_VMX_ULTRA_CLIENTID1TA_UUID = d70f3a8cc8dd11e69d9dcec0c932ce01
        TASK_STB_VMX_ULTRA_CLIENTID1TA_PATH = ${IMG_PATH}/${TASK_STB_VMX_ULTRA_CLIENTID1TA_NAME}.elf
        TASK_VMX_ULTRA_CLIENTID1TA_CFG = ${TASK_STB_VMX_ULTRA_CLIENTID1TA_PATH},${TASK_STB_VMX_ULTRA_CLIENTID1TA_NAME},${TASK_STB_VMX_ULTRA_CLIENTID1TA_UUID},0x1000
        TASK_HISI_LIST += ${TASK_VMX_ULTRA_CLIENTID1TA_CFG}
    endif
endif


ifeq ($(strip $(CFG_HI_TEE_VPSS_SUPPORT)), y)
	TASK_HISI_VPSS_NAME = task_hisi_vpss
	TASK_HISI_VPSS_UUID = 3acc8b1ba7e1e511b86d9a79f06e9478
	TASK_HISI_VPSS_PATH = ${IMG_PATH}/${TASK_HISI_VPSS_NAME}.elf
	TASK_HISI_VPSS_CFG = ${TASK_HISI_VPSS_PATH},${TASK_HISI_VPSS_NAME},${TASK_HISI_VPSS_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HISI_VPSS_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_DRM_SUPPORT)), y)
	TASK_HISI_DRM_NAME = task_stb_drm
	TASK_HISI_DRM_UUID = 14047d2df23648a0a0c4c1cccbb64546
	TASK_HISI_DRM_PATH = ${TRUSTEDCORE_DIR}/release/internal_tasks/${TASK_HISI_DRM_NAME}.elf
	TASK_HISI_DRM_CFG = ${TASK_HISI_DRM_PATH},${TASK_HISI_DRM_NAME},${TASK_HISI_DRM_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HISI_DRM_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_AVPLAY_SUPPORT)), y)
	TASK_HISI_AVPLAY_NAME = task_hisi_avplay
	TASK_HISI_AVPLAY_UUID = 99985ef1d62d45249dd1d9834548d98e
	TASK_HISI_AVPLAY_PATH = ${IMG_PATH}/${TASK_HISI_AVPLAY_NAME}.elf
	TASK_AVPLAY_CFG = ${TASK_HISI_AVPLAY_PATH},${TASK_HISI_AVPLAY_NAME},${TASK_HISI_AVPLAY_UUID},0x1000
	TASK_HISI_LIST += ${TASK_AVPLAY_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_NETFLIX_SUPPORT)), y)
	TASK_HISI_NETFLIX_NAME = task_hisi_netflix
	TASK_HISI_NETFLIX_UUID = 4c526126a26f452fb48f374c09386231
	TASK_HISI_NETFLIX_PATH = ${IMG_PATH}/${TASK_HISI_NETFLIX_NAME}.elf
	TASK_NETFLIX_CFG = ${TASK_HISI_NETFLIX_PATH},${TASK_HISI_NETFLIX_NAME},${TASK_HISI_NETFLIX_UUID},0x1000
	TASK_HISI_LIST += ${TASK_NETFLIX_CFG}
endif

ifeq ($(strip $(CFG_HI_TEE_CRYVER_SUPPORT)), y)
	TASK_HISI_CRYVER_NAME = task_cry_ver
	TASK_HISI_CRYVER_UUID = 46b8476642b011e6beb89e71128cae77
	TASK_HISI_CRYVER_PATH = ${IMG_PATH}/${TASK_HISI_CRYVER_NAME}.elf
	TASK_HISI_CRYVER_CFG = ${TASK_HISI_CRYVER_PATH},${TASK_HISI_CRYVER_NAME},${TASK_HISI_CRYVER_UUID},0x1000
	#Dynamic TA do not need pack to image
	ifneq ($(strip $(CFG_HI_TEE_TA_LOAD_SUPPORT)), y)
		TASK_HISI_LIST += ${TASK_HISI_CRYVER_CFG}
	endif
endif

ifeq ($(strip $(CFG_HI_TEE_STORAGE_TA_SUPPORT)), y)
	TASK_STORAGE_NAME = task_storage
	TASK_STORAGE_UUID = 02020202020202020202020202020202
	TASK_STORAGE_PATH = ${TRUSTEDCORE_DIR}/release/internal_tasks/${TASK_STORAGE_NAME}.elf
	TASK_STORAGE_CFG = ${TASK_STORAGE_PATH},${TASK_STORAGE_NAME},${TASK_STORAGE_UUID},0x1000
	TASK_HISI_LIST += ${TASK_STORAGE_CFG}
endif

#SUPPORT_SUMA
ifeq ($(strip $(CFG_HI_TEE_SUMA_SUPPORT)), y)
	TASK_SUMA_NAME = task_suma
	TASK_SUMA_UUID = db057c3e0eae11e793ae92361f002671
	TASK_SUMA_PATH = ${IMG_PATH}/${TASK_SUMA_NAME}.elf
	TASK_SUMA_CFG = ${TASK_SUMA_PATH},${TASK_SUMA_NAME},${TASK_SUMA_UUID},0x1000
	TASK_HISI_LIST +=${TASK_SUMA_CFG}
endif

#SUPPORT_SESSION MANAGE
ifeq ($(strip $(CFG_HI_TEE_SM_SUPPORT)), y)
	TASK_HISI_SM_NAME = task_hisi_session_manage
	TASK_HISI_SM_UUID = 90ae48e5c75744a7b513de4b2b14a07c
	TASK_HISI_SM_PATH = ${IMG_PATH}/${TASK_HISI_SM_NAME}.elf
	TASK_HISI_SM_CFG = ${TASK_HISI_SM_PATH},${TASK_HISI_SM_NAME},${TASK_HISI_SM_UUID},0x1000
	TASK_HISI_LIST += ${TASK_HISI_SM_CFG}
endif

PACKING_CFG = \
	"$(TRUSTEDCORE_TEXT_BASE)" \
	"$(PLATFORM_DIR_NAME)" \
	"$(OUT)" \
	"$(COMPARE_IMAGE)" \
	"$(TRUSTEDCORE_CHIP_CHOOSE)" \
	"$(PACKIMG_DEBUG_FLAG)" \
	"$(TASK_HISI_LIST)"
