#include "tee_common.h"
#include "uuid_disp.h"
#include "tee_config.h"
#include "tee_internal_api.h"
#include "ta_framework.h"
#include "sre_access_control.h"

#define DEFAULT_STACK_SIZE      0x4000
#define DEFAULT_HEAP_SIZE       0x10000
#ifdef TEE_DISABLE_CA_SIGN
const int g_tee_disable_ca_auth = TEE_DISABLE_CA_SIGN;
#else
const int g_tee_disable_ca_auth;
#endif
#define VFMW_TASK_STACK_SIZE    0x19000

/*build in service propertys */
const TA_property_t build_in_service_property[] = {
    /* uuid               stack  heap  permissions  instance  sessin  alive*/
#ifdef CFG_HI_TEE_TEST_TA_SUPPORT
    /* dymanic load */
    {TEE_SERVICE_ECHO,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   false, '0', NULL, 0},
    {TEE_SERVICE_UT,      DEFAULT_STACK_SIZE * 2, DEFAULT_HEAP_SIZE*4, true,     false,  false, '0', NULL, 0},
#endif
    {TEE_SERVICE_STORAGE, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     false,   true, '0', NULL, 0},
    {TEE_SERVICE_REET, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, false,   true, '0', NULL, 0},
    {TEE_SERVICE_SSA, DEFAULT_STACK_SIZE * 2, DEFAULT_HEAP_SIZE * 8, true,     false,   true, '0', NULL, 0},
	{TEE_SERVICE_RPMB, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE * 8, true,	   false,   true, '0', NULL, 0},
#ifdef CFG_HI_TEE_DEMO_SUPPORT
    {TEE_SERVICE_HISI_DEMO, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, false, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_SEC_MMZ_SUPPORT
    {TEE_SERVICE_SEC_MMZ, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_VFMW_SUPPORT
    {TEE_SERVICE_VFMW, VFMW_TASK_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_TEST_SUPPORT
    {TEE_SERVICE_HISI_TEST, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_SMMU_SUPPORT
    {TEE_SERVICE_SMMU, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_WIDEVINE_SUPPORT
    {TEE_SERVICE_WIDEVINE, DEFAULT_STACK_SIZE*12, DEFAULT_HEAP_SIZE*12, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_EMPTYDRM_SUPPORT
    {TEE_SERVICE_EMPTYDRM, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_PLAYREADY_SUPPORT
    {TEE_SERVICE_PLAYREADY, DEFAULT_STACK_SIZE*12, DEFAULT_HEAP_SIZE*18, true, true,   true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_DEMUX_SUPPORT
    {TEE_SERVICE_DMX, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_PLCIPHER_SUPPORT
    {TEE_SERVICE_PLCIPHER, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_CRYPTOEN_SUPPORT
    {TEE_SERVICE_CRYPTOEN, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif

#ifdef CFG_HI_TEE_PVR_SUPPORT
    {TEE_SERVICE_PVR, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_AVPLAY_SUPPORT
    {TEE_SERVICE_AVPLAY, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_NETFLIX_SUPPORT
    {TEE_SERVICE_NETFLIX, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_LOG_SUPPORT
    {TEE_SERVICE_LOG, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_HDMI_SUPPORT
    {TEE_SERVICE_HDMI, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#ifdef CFG_HI_TEE_VDP_SUPPORT
    {TEE_SERVICE_HISI_VDP, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#if defined(CFG_HI_TEE_VMX_ULTRA_SUPPORT) || defined(CFG_HI_TEE_VMXTAC_TEST_SUPPORT) \
    || defined(CFG_HI_TEE_ITAC_TEST_SUPPORT)
    {TEE_SERVICE_STB_VMX_ULTRA_VMXTA, DEFAULT_STACK_SIZE * 4, DEFAULT_HEAP_SIZE * 4, true, true, true, '0', NULL, 0},
    {TEE_SERVICE_STB_VMX_ULTRA_videomarkTA, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif
#if defined(CFG_HI_TEE_VMXTAC_TEST_SUPPORT) || defined(CFG_HI_TEE_ITAC_TEST_SUPPORT)
    {TEE_SERVICE_STB_VMX_ULTRA_VMXTAC_TEST_TA2, DEFAULT_STACK_SIZE * 2, DEFAULT_HEAP_SIZE * 2, true, true, true, '0', NULL, 0},
    {TEE_SERVICE_STB_VMX_ULTRA_VMXTAC_TEST_TA3, DEFAULT_STACK_SIZE * 2, DEFAULT_HEAP_SIZE * 2, true, true, true, '0', NULL, 0},
#endif

#ifdef CFG_HI_TEE_CRYVER_SUPPORT
    {TEE_SERVICE_CRYPTO_VERIFY, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     false,   true, '0', NULL, 0},
#endif

#ifdef CFG_HI_TEE_SUMA_SUPPORT
    {TEE_SERVICE_SUMA, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif

#ifdef CFG_HI_TEE_SM_SUPPORT
    {TEE_SERVICE_SESSION_MANAGE, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, true, true, '0', NULL, 0},
#endif

};

const uint32_t build_in_service_property_num = sizeof(build_in_service_property) / sizeof(build_in_service_property[0]);


const TEE_UUID build_in_uuid[] = {
    TEE_SERVICE_GLOBAL,
#ifdef CFG_HI_TEE_STORAGE_TA_SUPPORT
    TEE_SERVICE_STORAGE,
#endif
    TEE_SERVICE_REET,
    TEE_SERVICE_SSA,
    TEE_SERVICE_RPMB,
#ifdef CFG_HI_TEE_DEMO_SUPPORT
    TEE_SERVICE_HISI_DEMO,
#endif
#ifdef CFG_HI_TEE_SEC_MMZ_SUPPORT
    TEE_SERVICE_SEC_MMZ,
#endif
#ifdef CFG_HI_TEE_VFMW_SUPPORT
    TEE_SERVICE_VFMW,
#endif
#if CFG_HI_TEE_TEST_SUPPORT
    TEE_SERVICE_HISI_TEST,
#endif
#ifdef CFG_HI_TEE_SMMU_SUPPORT
    TEE_SERVICE_SMMU,
#endif
#if defined(CFG_HI_TEE_WIDEVINE_SUPPORT) && !defined(CFG_HI_TEE_TA_LOAD_SUPPORT)
    TEE_SERVICE_WIDEVINE,
#endif
#ifdef CFG_HI_TEE_EMPTYDRM_SUPPORT
    TEE_SERVICE_EMPTYDRM,
#endif
#if defined(CFG_HI_TEE_PLAYREADY_SUPPORT) && !defined(CFG_HI_TEE_TA_LOAD_SUPPORT)
    TEE_SERVICE_PLAYREADY,
#endif
#ifdef CFG_HI_TEE_DEMUX_SUPPORT
    TEE_SERVICE_DMX,
#endif
#ifdef CFG_HI_TEE_PLCIPHER_SUPPORT
    TEE_SERVICE_PLCIPHER,
#endif
#ifdef CFG_HI_TEE_CRYPTOEN_SUPPORT
    TEE_SERVICE_CRYPTOEN,
#endif
#ifdef CFG_HI_TEE_PVR_SUPPORT
    TEE_SERVICE_PVR,
#endif
#ifdef CFG_HI_TEE_AVPLAY_SUPPORT
    TEE_SERVICE_AVPLAY,
#endif
#ifdef CFG_HI_TEE_NETFLIX_SUPPORT
    TEE_SERVICE_NETFLIX,
#endif
#ifdef CFG_HI_TEE_LOG_SUPPORT
    TEE_SERVICE_LOG,
#endif
#ifdef CFG_HI_TEE_HDMI_SUPPORT
    TEE_SERVICE_HDMI,
#endif
#ifdef CFG_HI_TEE_VDP_SUPPORT
    TEE_SERVICE_HISI_VDP,
#endif
#if defined(CFG_HI_TEE_VMX_ULTRA_SUPPORT) || defined(CFG_HI_TEE_VMXTAC_TEST_SUPPORT) || defined(CFG_HI_TEE_ITAC_TEST_SUPPORT)
    TEE_SERVICE_STB_VMX_ULTRA_VMXTA,
    TEE_SERVICE_STB_VMX_ULTRA_videomarkTA,
#endif
#if defined(CFG_HI_TEE_VMXTAC_TEST_SUPPORT) || defined(CFG_HI_TEE_ITAC_TEST_SUPPORT)
    TEE_SERVICE_STB_VMX_ULTRA_VMXTAC_TEST_TA2,
    TEE_SERVICE_STB_VMX_ULTRA_VMXTAC_TEST_TA3,
#endif
#if defined(CFG_HI_TEE_CRYVER_SUPPORT) && !defined(CFG_HI_TEE_TA_LOAD_SUPPORT)
	/* Dynamic TA should not defined in build_in_uuid */
    TEE_SERVICE_CRYPTO_VERIFY,
#endif
#ifdef CFG_HI_TEE_SUMA_SUPPORT
    TEE_SERVICE_SUMA,
#endif
#ifdef CFG_HI_TEE_SM_SUPPORT
    TEE_SERVICE_SESSION_MANAGE,
#endif

};
const uint32_t build_in_service_num = sizeof(build_in_uuid) / sizeof(build_in_uuid[0]);

//TA permission control
const TA_permission_t ta_permission_config[] = {
    /*internal tasks*/
    {TEE_SERVICE_STORAGE, GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_REET, SMC_GROUP_PERMISSION},
    {TEE_SERVICE_SSA, (GENERAL_GROUP_PERMISSION | CC_KEY_GROUP2_PERMISSION | MM_GROUP_PERMISSION)},
	{TEE_SERVICE_RPMB,	 RPMB_GENERIC_PERMISSION | RPMB_SPECIFIC_PERMISSION | CC_KEY_GROUP2_PERMISSION | RPMB_UPDATE_PERMISSION | MM_GROUP_PERMISSION},
    /*dymanic tasks*/
#ifdef CFG_HI_TEE_TEST_TA_SUPPORT
    {TEE_SERVICE_ECHO, ALL_GROUP_PERMISSION},
    {TEE_SERVICE_UT,      ALL_GROUP_PERMISSION},
    {TEE_SERVICE_TIMER_UT,    TIMER_GROUP_PERMISSION},
#endif

#ifdef CFG_HI_TEE_DEMO_SUPPORT
    {TEE_SERVICE_HISI_DEMO, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_CRYVER_SUPPORT
    {TEE_SERVICE_CRYPTO_VERIFY, GENERAL_GROUP_PERMISSION},
#endif
#if defined(CFG_HI_TEE_VMX_ULTRA_SUPPORT) || defined(CFG_HI_TEE_VMXTAC_TEST_SUPPORT) || defined(CFG_HI_TEE_ITAC_TEST_SUPPORT)
    {TEE_SERVICE_STB_VMX_ULTRA_VMXTA,           GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_STB_VMX_ULTRA_videomarkTA,     GENERAL_GROUP_PERMISSION},
#endif
#if defined(CFG_HI_TEE_VMXTAC_TEST_SUPPORT) || defined(CFG_HI_TEE_ITAC_TEST_SUPPORT)
    {TEE_SERVICE_STB_VMX_ULTRA_VMXTAC_TEST_TA2, GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_STB_VMX_ULTRA_VMXTAC_TEST_TA3, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_WIDEVINE_SUPPORT
    {TEE_SERVICE_WIDEVINE,    GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_EMPTYDRM_SUPPORT
    {TEE_SERVICE_EMPTYDRM,    GENERAL_GROUP_PERMISSION | MM_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_PLAYREADY_SUPPORT
    {TEE_SERVICE_PLAYREADY,    GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_SEC_MMZ_SUPPORT
    {TEE_SERVICE_SEC_MMZ, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_VFMW_SUPPORT
    {TEE_SERVICE_VFMW, GENERAL_GROUP_PERMISSION},
#endif
#if CFG_HI_TEE_TEST_SUPPORT
    {TEE_SERVICE_HISI_TEST, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_SMMU_SUPPORT
    {TEE_SERVICE_SMMU, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_DEMUX_SUPPORT
    {TEE_SERVICE_DMX, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_PLCIPHER_SUPPORT
    {TEE_SERVICE_PLCIPHER, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_CRYPTOEN_SUPPORT
    {TEE_SERVICE_CRYPTOEN, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_VDP_SUPPORT
    {TEE_SERVICE_HISI_VDP, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_PVR_SUPPORT
    {TEE_SERVICE_PVR, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_AVPLAY_SUPPORT
    {TEE_SERVICE_AVPLAY, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_NETFLIX_SUPPORT
    {TEE_SERVICE_NETFLIX, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_LOG_SUPPORT
    {TEE_SERVICE_LOG, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_HDMI_SUPPORT
    {TEE_SERVICE_HDMI, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_SUMA_SUPPORT
    {TEE_SERVICE_HDMI, GENERAL_GROUP_PERMISSION},
#endif
#ifdef CFG_HI_TEE_SM_SUPPORT
    {TEE_SERVICE_SESSION_MANAGE, GENERAL_GROUP_PERMISSION},
#endif
};
const uint32_t dynamic_ta_num = sizeof(ta_permission_config) / sizeof(ta_permission_config[0]);

const TA_rpmb_threshold_t ta_rpmb_threshold_config[] = {
    /* DO NOT EDIT */
#if defined(CFG_HI_TEE_TEST_TA_SUPPORT)
	{TEE_SERVICE_UT, 0x100000},
#endif
    /* DO NOT EDIT */
#ifdef CFG_HI_TEE_DEMO_SUPPORT
    {TEE_SERVICE_HISI_DEMO, 32 * 1024},
#endif
};
const uint32_t g_rpmb_ta_num = sizeof(ta_rpmb_threshold_config) / sizeof(ta_rpmb_threshold_config[0]);

TA_permission_t rpmb_permission_config[] = {
       {TEE_SERVICE_RPMB,  RPMB_GENERIC_PERMISSION | RPMB_SPECIFIC_PERMISSION | RPMB_UPDATE_PERMISSION},
       {TEE_SERVICE_HISI_DEMO, RPMB_GENERIC_PERMISSION},
       {TEE_SERVICE_ECHO,  RPMB_GENERIC_PERMISSION | RPMB_SPECIFIC_PERMISSION},
       {TEE_SERVICE_UT,        RPMB_GENERIC_PERMISSION | RPMB_SPECIFIC_PERMISSION},
       {TEE_SERVICE_KEYMASTER, RPMB_GENERIC_PERMISSION},
       {TEE_SERVICE_KERNELMEMUSAGE,      RPMB_GENERIC_PERMISSION | RPMB_SPECIFIC_PERMISSION},
       {TEE_SERVICE_FINGERPRINT,RPMB_GENERIC_PERMISSION},
       {TEE_SERVICE_RPMBKEY,    RPMB_GENERIC_PERMISSION | RPMB_SPECIFIC_PERMISSION},
       {TEE_SERVICE_SIGNTOOL,   RPMB_GENERIC_PERMISSION},
       {TEE_SERVICE_SKYTONE,    RPMB_GENERIC_PERMISSION},
       {TEE_SERVICE_Antitheft,  RPMB_GENERIC_PERMISSION},
       {TEE_SERVICE_IFAA,       RPMB_GENERIC_PERMISSION},
};
uint32_t g_rpmb_permission_num = sizeof(rpmb_permission_config) / sizeof(TA_permission_t);