HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_OPMODE_NOTIFY
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_20_40_80_COEXIST
HI1131_WIFI_CFLAGS +=-D_PRE_CHIP_BITS_MIPS64=1
HI1131_WIFI_CFLAGS +=-D_PRE_CHIP_BITS_MIPS32=0
HI1131_WIFI_CFLAGS +=-D_PRE_CHIP_BITS=_PRE_CHIP_BITS_MIPS32

HI1131_WIFI_CFLAGS +=-D_PRE_OS_VERSION_LINUX=0 
HI1131_WIFI_CFLAGS +=-D_PRE_OS_VERSION_WIN32=1 
HI1131_WIFI_CFLAGS +=-D_PRE_OS_VERSION_WINDOWS=2 
HI1131_WIFI_CFLAGS +=-D_PRE_OS_VERSION_RAW=3 
HI1131_WIFI_CFLAGS +=-D_PRE_OS_VERSION_HiRTOS=4 
HI1131_WIFI_CFLAGS +=-D_PRE_OS_VERSION_LITEOS=5 
HI1131_WIFI_CFLAGS +=-D_PRE_OS_VERSION=_PRE_OS_VERSION_LITEOS

HI1131_WIFI_CFLAGS +=-D_PRE_TEST_MODE_OFF=0
HI1131_WIFI_CFLAGS +=-D_PRE_TEST_MODE_UT=1
HI1131_WIFI_CFLAGS +=-D_PRE_TEST_MODE_ST=2
HI1131_WIFI_CFLAGS +=-D_PRE_TEST_MODE_BOARD_ST=3
HI1131_WIFI_CFLAGS +=-D_PRE_TEST_MODE=_PRE_TEST_MODE_OFF

#1131
HI1131_WIFI_CFLAGS +=-D_PRE_HW_DEVICE_REGISTER_WITP=0
HI1131_WIFI_CFLAGS +=-D_PRE_HW_DEVICE_REGISTER_HI1102=1
HI1131_WIFI_CFLAGS +=-D_PRE_HW_DEVICE_VERSION=_PRE_HW_DEVICE_REGISTER_HI1102

HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID_WITP=0
HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID_HI1151=1 
HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID_HI1152=2 
HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID_HI1102_DEV=3 
HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID_HI1102_HOST=4
HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID_HI1131C_DEV=5
HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID_HI1131C_HOST=6
HI1131_WIFI_CFLAGS +=-D_PRE_PRODUCT_ID=_PRE_PRODUCT_ID_HI1131C_HOST

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_SIM_CHIP=0
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_REAL_CHIP=1
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_CHIP_SIM=_PRE_WLAN_REAL_CHIP

HI1131_WIFI_CFLAGS +=-D_PRE_MULTI_CORE_MODE_SMP=0
HI1131_WIFI_CFLAGS +=-D_PRE_MULTI_CORE_MODE_PIPELINE_AMP=1
HI1131_WIFI_CFLAGS +=-D_PRE_MULTI_CORE_MODE_OFFLOAD_HMAC=2
HI1131_WIFI_CFLAGS +=-D_PRE_MULTI_CORE_MODE_OFFLOAD_DMAC=3
HI1131_WIFI_CFLAGS +=-D_PRE_MULTI_CORE_MODE=_PRE_MULTI_CORE_MODE_OFFLOAD_DMAC
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_CUSTOM_SECURITY

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_11D
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_DFT_STAT
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_DFT_DUMP_FRAME

HI1131_WIFI_CFLAGS +=-D_PRE_BIG_CPU_ENDIAN=0
HI1131_WIFI_CFLAGS +=-D_PRE_LITTLE_CPU_ENDIAN=1
HI1131_WIFI_CFLAGS +=-D_PRE_CPU_ENDIAN=_PRE_LITTLE_CPU_ENDIAN
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_TCP_UDP_KEEPALIVE
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_DFT_STAT
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_NEW_IQ
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_DFR



ifndef DBG_ALG_ENABLE
export DBG_ALG_ENABLE=n
endif
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_TXBF

ifeq ($(DBG_ALG_ENABLE), y)
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_ALG_ENABLE
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_AUTORATE
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_SCHEDULE
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_TRAFFIC_CTL
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_FLOWCTL
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_MVAP_SCH
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_PERFORM_STAT
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_PERFORM_TPC
HI1131_WIFI_CFLAGS +=-D_PRE_SUPPORT_FCS
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_DBAC
HI1131_WIFI_CFLAGS +=-D_PRE_DBAC_DYNAMIC_POLICY
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_AGGR_OPTIMIZE
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_TXBF

#HI1131_WIFI_CFLAGS +=-D_PRE_SUPPORT_SCANNER
#HI1131_WIFI_CFLAGS +=-D_PRE_SUPPORT_ACS
#HI1131_WIFI_CFLAGS +=-D_PRE_SUPPORT_DFS

else

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_OFFLOAD_FLOWCTL
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_DBAC
endif

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_TX_CLASSIFY_LAN_TO_WLAN
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_CLASSIFY
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_ALWAYS_TX
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_WPA
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_WPA2
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_AMPDU
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_DFS
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_AMSDU
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_ARP_OFFLOAD
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_EDCA_OPT_AP
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_PKT_MEM_OPT

ifeq ($(BOARD_FUNC), DG)
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FPGA_DIGITAL
endif

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_DFT_LOG


HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_P2P
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_CHIP_TEST_ALG

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_STA_PM
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_STA_UAPSD
HI1131_WIFI_CFLAGS +=-D_PRE_PSM_DEBUG_MODE
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_BTCOEX
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_LTECOEX
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_RF_110X_CALI_DPD

#11ac2g support
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_11AC2G
#uapsd support
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_UAPSD
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_TXOPPS
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_WAPI
HI1131_WIFI_CFLAGS +=-D_PRE_WAPI_DEBUG


#tcp ack optimize
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_TCP_OPT
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_PROFLING_SOC
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_PROFLING_MIPS

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_AMPDU_VAP

#hs20 character open
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_HS20

#auto_freq adjust
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_AUTO_FREQ

# set debug options
#DEBFLAGS = -Wall -O2 -g -DSCULL_DEBUG -DEXPORT_SYMTAB

#roam support
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_ROAM

HI1131_WIFI_CFLAGS +=-DCONFIG_MMC
HI1131_WIFI_CFLAGS +=-DCONFIG_HI110X_SDIO_STD_CARD_SUPPORT

HI1131_WIFI_CFLAGS +=-DNEED_AP_MLME
#HI1131_WIFI_CFLAGS +=-D_PRE_DEBUG_MODE

HI1131_WIFI_CFLAGS +=-DCONFIG_PRINTK
HI1131_WIFI_CFLAGS +=-D_PRE_FRW_FEATURE_PROCCESS_ENTITY_THREAD=0
HI1131_WIFI_CFLAGS +=-D_PRE_FRW_FEATURE_PROCCESS_ENTITY_TASKLET=1
HI1131_WIFI_CFLAGS +=-D_PRE_FRW_FEATURE_PROCCESS_ENTITY_TYPE=_PRE_FRW_FEATURE_PROCCESS_ENTITY_THREAD

#add by  ,for print log
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_HWAL_LAYER
HI1131_WIFI_CFLAGS +=-DOAM_SDT_OUT
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_DEBUG_LOG
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_RXTX_TICK

#add by  ,for rekey offload
#HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_REKEY_OFFLOAD

#add by , for lwip_zero_copy
#HI1131_WIFI_CFLAGS +=-D_PRE_LWIP_ZERO_COPY_DEBUG

HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_HILINK
HI1131_WIFI_CFLAGS +=-D_PRE_PMF_NOT_SUPPORT=0
HI1131_WIFI_CFLAGS +=-D_PRE_PMF_HW_CCMP_SW_BIP=1
HI1131_WIFI_CFLAGS +=-D_PRE_PMF_HW_CCMP_BIP=2
HI1131_WIFI_CFLAGS +=-D_PRE_WLAN_FEATURE_PMF=_PRE_PMF_HW_CCMP_BIP

#customize
HI1131_WIFI_CFLAGS +=-D_PRE_PLAT_FEATURE_CUSTOMIZE
