#if defined(HI_ADVCA_FUNCTION_RELEASE) && !defined(NO_HI_ADVCA_FUNCTION_RELEASE)
#ifdef PNG_ERROR_TEXT_SUPPORTED
#undef PNG_ERROR_TEXT_SUPPORTED
#endif

#ifdef PNG_WARNINGS_SUPPORTED
#undef PNG_WARNINGS_SUPPORTED
#endif

#ifdef PNG_BENIGN_ERRORS_SUPPORTED
#undef PNG_BENIGN_ERRORS_SUPPORTED
#endif

#endif