obj-$(CONFIG_ION) += hisi_ion_device.o hisi_ion.o
subdir-ccflags-$(CONFIG_TZDRIVER) += -Idrivers/hisilicon/tee/tee_hisi/tzdriver/
subdir-ccflags-$(CONFIG_OPTEE) += -Idrivers/tee/optee/

obj-$(CONFIG_TEE) += tee_smmu.o
