
obj-y += kapi/ misc/ soc/ clk/ atags/ flash_stats/ ir/

obj-$(CONFIG_BLK_DEV_RAM)		+= initmrd/
obj-$(CONFIG_BLK_DEV_LOOP)		+= initfile/
obj-$(CONFIG_VIRTUAL_INPUT)		+= vinput/
obj-$(CONFIG_CMA)			+= cma/
obj-$(CONFIG_USB_OTG_HISI)		+= usbotg/

obj-$(CONFIG_TEE)			+= sec_mmz/
obj-$(CONFIG_TEE)			+= tee/
obj-$(CONFIG_REGULATOR)			+= regulator/
obj-$(CONFIG_HASH_VRF_DEV)		+= hash_vrf_dev/
obj-$(CONFIG_THERMAL)			+= thermal/
obj-$(CONFIG_PCIE_HISILICON)		+= pcie/
obj-$(CONFIG_DEVFREQ_GOV_GPU_ONDEMAND)	+= devfreq/
