#ifndef __HAL_IP_SNR_H__
#define __HAL_IP_SNR_H__
#if EDA_TEST
#include <stdio.h>
#include <stdlib.h>
#include <vdp_assert.h>
#endif

//#include "c_union_define.h"
#include "vdp_define.h"

////SNR
HI_VOID VDP_VID_SetSnrEnable                        (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetSnrCfgAddr                       (HI_U32 u32Data, HI_U32 u32Addr);
#if 0
HI_VOID VDP_VID_SetSnrMadRAddr                      (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetSNRYnr2DEnable                   (HI_U32 u32Data,HI_U32 ynr2den);
HI_VOID VDP_VID_SetSNRCnr2DEnable                   (HI_U32 u32Data,HI_U32 cnr2den);
HI_VOID VDP_VID_SetSNRMotionEdgeWeightEnable        (HI_U32 u32Data,HI_U32 motionedgeweighten);
HI_VOID VDP_VID_SetSNRColorWeightEnable             (HI_U32 u32Data,HI_U32 colorweighten);
HI_VOID VDP_VID_SetSNREdgePreFilerEnable            (HI_U32 u32Data,HI_U32 edgeprefilteren);
HI_VOID VDP_VID_SetSNRMarketModeEnable              (HI_U32 u32Data,HI_U32 marketen);
HI_VOID VDP_VID_SetSNRMarketModeMux                 (HI_U32 u32Data,HI_U32 market_mux);
HI_VOID VDP_VID_SetSNRTestModeEnable                (HI_U32 u32Data,HI_U32 test_en);
HI_VOID VDP_VID_SetSNREdgeRatioRange                (HI_U32 u32Data,HI_U32 edgemaxratio, HI_U32 edgeminratio, HI_U32 edgeoriratio);
HI_VOID VDP_VID_SetSNREdgeStrRange                  (HI_U32 u32Data,HI_U32 edgemaxstrength, HI_U32 edgeminstrength, HI_U32 edgeoristrength);
HI_VOID VDP_VID_SetSNREdgeStrth                     (HI_U32 u32Data,HI_U32 edgestrth1, HI_U32 edgestrth2, HI_U32 edgestrth3);
HI_VOID VDP_VID_SetSNREdgeStrk                      (HI_U32 u32Data,HI_U32 edgestrk1, HI_U32 edgestrk2, HI_U32 edgestrk3);
HI_VOID VDP_VID_SetSNREdgeMeanth1                   (HI_U32 u32Data,HI_U32 edgemeanth1, HI_U32 edgemeanth2, HI_U32 edgemeanth3);
HI_VOID VDP_VID_SetSNREdgeMeanth2                   (HI_U32 u32Data,HI_U32 edgemeanth4, HI_U32 edgemeanth5, HI_U32 edgemeanth6);
HI_VOID VDP_VID_SetSNREdgeMeanth3                   (HI_U32 u32Data,HI_U32 edgemeanth7, HI_U32 edgemeanth8);
HI_VOID VDP_VID_SetSNREdgeMeank1                    (HI_U32 u32Data,HI_U32 edgemeank1, HI_U32 edgemeank2, HI_U32 edgemeank3, HI_U32 edgemeank4);
HI_VOID VDP_VID_SetSNREdgeMeank2                    (HI_U32 u32Data,HI_U32 edgemeank5, HI_U32 edgemeank6, HI_U32 edgemeank7, HI_U32 edgemeank8);
HI_VOID VDP_VID_SetSNRWin                           (HI_U32 u32Data,HI_U32 y2dwinwidth, HI_U32 y2dwinheight, HI_U32 c2dwinwidth, HI_U32 c2dwinheight);
HI_VOID VDP_VID_SetSNRStr                           (HI_U32 u32Data,HI_U32 ysnrstr, HI_U32 csnrstr);
HI_VOID VDP_VID_SetSNROffset                        (HI_U32 u32Data,HI_U32 stroffset0, HI_U32 stroffset1, HI_U32 stroffset2, HI_U32 stroffset3);
HI_VOID VDP_VID_SetSNRAdjust                        (HI_U32 u32Data,HI_U32 ystradjust, HI_U32 cstradjust);
HI_VOID VDP_VID_SetSNRSChangeTh                     (HI_U32 u32Data,HI_U32 scenechangeth);
HI_VOID VDP_VID_SetSNRRatio1                        (HI_U32 u32Data,HI_U32 ratio1, HI_U32 ratio2, HI_U32 ratio3);
HI_VOID VDP_VID_SetSNRRatio2                        (HI_U32 u32Data,HI_U32 ratio4, HI_U32 ratio5, HI_U32 ratio6);
HI_VOID VDP_VID_SetSNRRatio3                        (HI_U32 u32Data,HI_U32 ratio7, HI_U32 ratio8);
HI_VOID VDP_VID_SetSNREdgeStr                       (HI_U32 u32Data,HI_U32 edge1, HI_U32 edge2, HI_U32 edge3);
HI_VOID VDP_VID_SetSNRTestColor                     (HI_U32 u32Data,HI_U32 test_color_cb, HI_U32 test_color_cr);
HI_VOID VDP_VID_SetSNRSChange                       (HI_U32 u32Data,HI_U32 scenechange_info, HI_U32 scenechange_en, HI_U32 scenechange_mode1_en, HI_U32 scenechange_bldk, HI_S32 scenechange_bldcore, HI_U32 scenechange_mode2_en);
HI_VOID VDP_VID_SetSNRMotionEdgeLut                 (HI_U32 u32Data,HI_U32 motion_edge_lut[32]);
HI_VOID VDP_VID_SetSNRColorBasedLut                 (HI_U32 u32Data,HI_U32 color_based_lut[32]);
#endif
HI_VOID VDP_VID_SetSnrstrength                      (HI_U32 u32Data, HI_U32 snrstrength);
HI_VOID VDP_VID_SetSnrfiltermode                    (HI_U32 u32Data, HI_U32 snrfiltermode);
HI_VOID VDP_VID_SetMeanedgeratioen                  (HI_U32 u32Data, HI_U32 meanedgeratioen);
HI_VOID VDP_VID_SetEdgelpfmode                      (HI_U32 u32Data, HI_U32 edgelpfmode);
HI_VOID VDP_VID_SetDiredgesmoothen                  (HI_U32 u32Data, HI_U32 diredgesmoothen);
HI_VOID VDP_VID_SetDebugmode                        (HI_U32 u32Data, HI_U32 debugmode);
HI_VOID VDP_VID_SetDebugmodeen                      (HI_U32 u32Data, HI_U32 debugmodeen);
HI_VOID VDP_VID_SetDemomodelr                       (HI_U32 u32Data, HI_U32 demomodelr);
HI_VOID VDP_VID_SetDemomodeen                       (HI_U32 u32Data, HI_U32 demomodeen);
HI_VOID VDP_VID_SetBlendingmode                     (HI_U32 u32Data, HI_U32 blendingmode);
HI_VOID VDP_VID_SetEdgeonlyen                       (HI_U32 u32Data, HI_U32 edgeonlyen);
HI_VOID VDP_VID_SetMotionedgeen                     (HI_U32 u32Data, HI_U32 motionedgeen);
HI_VOID VDP_VID_SetColorweighten                    (HI_U32 u32Data, HI_U32 colorweighten);
HI_VOID VDP_VID_SetEdgeprelpfen                     (HI_U32 u32Data, HI_U32 edgeprelpfen);
HI_VOID VDP_VID_SetChromasnren                      (HI_U32 u32Data, HI_U32 chromasnren);
HI_VOID VDP_VID_SetLumasnren                        (HI_U32 u32Data, HI_U32 lumasnren);
HI_VOID VDP_VID_SetMeanedgeratiox2                  (HI_U32 u32Data, HI_U32 meanedgeratiox2);
HI_VOID VDP_VID_SetMeanedgeratiox1                  (HI_U32 u32Data, HI_U32 meanedgeratiox1);
HI_VOID VDP_VID_SetMeanedgeratiox0                  (HI_U32 u32Data, HI_U32 meanedgeratiox0);
HI_VOID VDP_VID_SetMeanedgeratiox5                  (HI_U32 u32Data, HI_U32 meanedgeratiox5);
HI_VOID VDP_VID_SetMeanedgeratiox4                  (HI_U32 u32Data, HI_U32 meanedgeratiox4);
HI_VOID VDP_VID_SetMeanedgeratiox3                  (HI_U32 u32Data, HI_U32 meanedgeratiox3);
HI_VOID VDP_VID_SetMeanedgeratioy2                  (HI_U32 u32Data, HI_U32 meanedgeratioy2);
HI_VOID VDP_VID_SetMeanedgeratioy1                  (HI_U32 u32Data, HI_U32 meanedgeratioy1);
HI_VOID VDP_VID_SetMeanedgeratioy0                  (HI_U32 u32Data, HI_U32 meanedgeratioy0);
HI_VOID VDP_VID_SetMeanedgeratioy4                  (HI_U32 u32Data, HI_U32 meanedgeratioy4);
HI_VOID VDP_VID_SetMeanedgeratioy3                  (HI_U32 u32Data, HI_U32 meanedgeratioy3);
HI_VOID VDP_VID_SetMeanedgeratiok1                  (HI_U32 u32Data, HI_U32 meanedgeratiok1);
HI_VOID VDP_VID_SetMeanedgeratiok0                  (HI_U32 u32Data, HI_U32 meanedgeratiok0);
HI_VOID VDP_VID_SetMeanedgeratiok3                  (HI_U32 u32Data, HI_U32 meanedgeratiok3);
HI_VOID VDP_VID_SetMeanedgeratiok2                  (HI_U32 u32Data, HI_U32 meanedgeratiok2);
HI_VOID VDP_VID_SetMeanedgeratiomin                 (HI_U32 u32Data, HI_U32 meanedgeratiomin);
HI_VOID VDP_VID_SetMeanedgeratiomax                 (HI_U32 u32Data, HI_U32 meanedgeratiomax);
HI_VOID VDP_VID_SetEdgestrmappingx2                 (HI_U32 u32Data, HI_U32 edgestrmappingx2);
HI_VOID VDP_VID_SetEdgestrmappingx1                 (HI_U32 u32Data, HI_U32 edgestrmappingx1);
HI_VOID VDP_VID_SetEdgestrmappingx0                 (HI_U32 u32Data, HI_U32 edgestrmappingx0);
HI_VOID VDP_VID_SetEdgestrmappingx5                 (HI_U32 u32Data, HI_U32 edgestrmappingx5);
HI_VOID VDP_VID_SetEdgestrmappingx4                 (HI_U32 u32Data, HI_U32 edgestrmappingx4);
HI_VOID VDP_VID_SetEdgestrmappingx3                 (HI_U32 u32Data, HI_U32 edgestrmappingx3);
HI_VOID VDP_VID_SetEdgestrmappingx7                 (HI_U32 u32Data, HI_U32 edgestrmappingx7);
HI_VOID VDP_VID_SetEdgestrmappingx6                 (HI_U32 u32Data, HI_U32 edgestrmappingx6);
HI_VOID VDP_VID_SetEdgestrmappingy3                 (HI_U32 u32Data, HI_U32 edgestrmappingy3);
HI_VOID VDP_VID_SetEdgestrmappingy2                 (HI_U32 u32Data, HI_U32 edgestrmappingy2);
HI_VOID VDP_VID_SetEdgestrmappingy1                 (HI_U32 u32Data, HI_U32 edgestrmappingy1);
HI_VOID VDP_VID_SetEdgestrmappingy0                 (HI_U32 u32Data, HI_U32 edgestrmappingy0);
HI_VOID VDP_VID_SetEdgestrmappingy6                 (HI_U32 u32Data, HI_U32 edgestrmappingy6);
HI_VOID VDP_VID_SetEdgestrmappingy5                 (HI_U32 u32Data, HI_U32 edgestrmappingy5);
HI_VOID VDP_VID_SetEdgestrmappingy4                 (HI_U32 u32Data, HI_U32 edgestrmappingy4);
HI_VOID VDP_VID_SetEdgestrmappingk2                 (HI_U32 u32Data, HI_U32 edgestrmappingk2);
HI_VOID VDP_VID_SetEdgestrmappingk1                 (HI_U32 u32Data, HI_U32 edgestrmappingk1);
HI_VOID VDP_VID_SetEdgestrmappingk0                 (HI_U32 u32Data, HI_U32 edgestrmappingk0);
HI_VOID VDP_VID_SetEdgestrmappingk5                 (HI_U32 u32Data, HI_U32 edgestrmappingk5);
HI_VOID VDP_VID_SetEdgestrmappingk4                 (HI_U32 u32Data, HI_U32 edgestrmappingk4);
HI_VOID VDP_VID_SetEdgestrmappingk3                 (HI_U32 u32Data, HI_U32 edgestrmappingk3);
HI_VOID VDP_VID_SetEdgestrmappingmax                (HI_U32 u32Data, HI_U32 edgestrmappingmax);
HI_VOID VDP_VID_SetEdgestrmappingmin                (HI_U32 u32Data, HI_U32 edgestrmappingmin);
HI_VOID VDP_VID_SetSfymaxedgevalthd3                (HI_U32 u32Data, HI_U32 sfymaxedgevalthd3);
HI_VOID VDP_VID_SetSfymaxedgevalthd2                (HI_U32 u32Data, HI_U32 sfymaxedgevalthd2);
HI_VOID VDP_VID_SetSfymaxedgevalthd1                (HI_U32 u32Data, HI_U32 sfymaxedgevalthd1);
HI_VOID VDP_VID_SetSfymaxedgeidxthd3                (HI_U32 u32Data, HI_U32 sfymaxedgeidxthd3);
HI_VOID VDP_VID_SetSfymaxedgeidxthd2                (HI_U32 u32Data, HI_U32 sfymaxedgeidxthd2);
HI_VOID VDP_VID_SetSfymaxedgeidxthd1                (HI_U32 u32Data, HI_U32 sfymaxedgeidxthd1);
HI_VOID VDP_VID_SetSfymeanedgevalthd3               (HI_U32 u32Data, HI_U32 sfymeanedgevalthd3);
HI_VOID VDP_VID_SetSfymeanedgevalthd2               (HI_U32 u32Data, HI_U32 sfymeanedgevalthd2);
HI_VOID VDP_VID_SetSfymeanedgevalthd1               (HI_U32 u32Data, HI_U32 sfymeanedgevalthd1);
HI_VOID VDP_VID_SetWfymaxedgevalthd3                (HI_U32 u32Data, HI_U32 wfymaxedgevalthd3);
HI_VOID VDP_VID_SetWfymaxedgevalthd2                (HI_U32 u32Data, HI_U32 wfymaxedgevalthd2);
HI_VOID VDP_VID_SetWfymaxedgevalthd1                (HI_U32 u32Data, HI_U32 wfymaxedgevalthd1);
HI_VOID VDP_VID_SetWfymaxedgeidxthd3                (HI_U32 u32Data, HI_U32 wfymaxedgeidxthd3);
HI_VOID VDP_VID_SetWfymaxedgeidxthd2                (HI_U32 u32Data, HI_U32 wfymaxedgeidxthd2);
HI_VOID VDP_VID_SetWfymaxedgeidxthd1                (HI_U32 u32Data, HI_U32 wfymaxedgeidxthd1);
HI_VOID VDP_VID_SetWfymeanedgevalthd3               (HI_U32 u32Data, HI_U32 wfymeanedgevalthd3);
HI_VOID VDP_VID_SetWfymeanedgevalthd2               (HI_U32 u32Data, HI_U32 wfymeanedgevalthd2);
HI_VOID VDP_VID_SetWfymeanedgevalthd1               (HI_U32 u32Data, HI_U32 wfymeanedgevalthd1);
HI_VOID VDP_VID_SetSfcmaxedgevalthd2                (HI_U32 u32Data, HI_U32 sfcmaxedgevalthd2);
HI_VOID VDP_VID_SetSfcmaxedgevalthd1                (HI_U32 u32Data, HI_U32 sfcmaxedgevalthd1);
HI_VOID VDP_VID_SetSfcmaxedgeidxthd2                (HI_U32 u32Data, HI_U32 sfcmaxedgeidxthd2);
HI_VOID VDP_VID_SetSfcmaxedgeidxthd1                (HI_U32 u32Data, HI_U32 sfcmaxedgeidxthd1);
HI_VOID VDP_VID_SetSfcmeanedgevalthd2               (HI_U32 u32Data, HI_U32 sfcmeanedgevalthd2);
HI_VOID VDP_VID_SetSfcmeanedgevalthd1               (HI_U32 u32Data, HI_U32 sfcmeanedgevalthd1);
HI_VOID VDP_VID_SetWfcmaxedgevalthd2                (HI_U32 u32Data, HI_U32 wfcmaxedgevalthd2);
HI_VOID VDP_VID_SetWfcmaxedgevalthd1                (HI_U32 u32Data, HI_U32 wfcmaxedgevalthd1);
HI_VOID VDP_VID_SetWfcmaxedgeidxthd2                (HI_U32 u32Data, HI_U32 wfcmaxedgeidxthd2);
HI_VOID VDP_VID_SetWfcmaxedgeidxthd1                (HI_U32 u32Data, HI_U32 wfcmaxedgeidxthd1);
HI_VOID VDP_VID_SetWfcmeanedgevalthd2               (HI_U32 u32Data, HI_U32 wfcmeanedgevalthd2);
HI_VOID VDP_VID_SetWfcmeanedgevalthd1               (HI_U32 u32Data, HI_U32 wfcmeanedgevalthd1);
HI_VOID VDP_VID_SetCdefaultfiltertype               (HI_U32 u32Data, HI_U32 cdefaultfiltertype);
HI_VOID VDP_VID_SetYdefaultfiltertype               (HI_U32 u32Data, HI_U32 ydefaultfiltertype);
HI_VOID VDP_VID_SetNonoisegain                      (HI_U32 u32Data, HI_U32 nonoisegain);
HI_VOID VDP_VID_SetNoisecore                        (HI_U32 u32Data, HI_U32 noisecore);
HI_VOID VDP_VID_SetRandyinnoiselevel                (HI_U32 u32Data, HI_U32 randyinnoiselevel);
HI_VOID VDP_VID_SetAddrandyinnoiseen                (HI_U32 u32Data, HI_U32 addrandyinnoiseen);
HI_VOID VDP_VID_SetDiffabssumofst                   (HI_U32 u32Data, HI_U32 diffabssumofst);
HI_VOID VDP_VID_SetSclabssum                        (HI_U32 u32Data, HI_U32 sclabssum);
HI_VOID VDP_VID_SetEdgeindicatorsel                 (HI_U32 u32Data, HI_U32 edgeindicatorsel);
HI_VOID VDP_VID_SetWinactdirdiffthr                 (HI_U32 u32Data, HI_U32 winactdirdiffthr);
HI_VOID VDP_VID_SetWinactthr                        (HI_U32 u32Data, HI_U32 winactthr);
HI_VOID VDP_VID_SetPixdirstrthr1                    (HI_U32 u32Data, HI_U32 pixdirstrthr1);
HI_VOID VDP_VID_SetPixdirstrthr0                    (HI_U32 u32Data, HI_U32 pixdirstrthr0);
HI_VOID VDP_VID_SetPixdirstrthr3                    (HI_U32 u32Data, HI_U32 pixdirstrthr3);
HI_VOID VDP_VID_SetPixdirstrthr2                    (HI_U32 u32Data, HI_U32 pixdirstrthr2);
HI_VOID VDP_VID_SetPixdirstrthr5                    (HI_U32 u32Data, HI_U32 pixdirstrthr5);
HI_VOID VDP_VID_SetPixdirstrthr4                    (HI_U32 u32Data, HI_U32 pixdirstrthr4);
HI_VOID VDP_VID_SetPixdirstrthr7                    (HI_U32 u32Data, HI_U32 pixdirstrthr7);
HI_VOID VDP_VID_SetPixdirstrthr6                    (HI_U32 u32Data, HI_U32 pixdirstrthr6);
HI_VOID VDP_VID_SetMediff3thrdir0                   (HI_U32 u32Data, HI_U32 mediff3thrdir0);
HI_VOID VDP_VID_SetMediffcntmintenthrdir0           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir0);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir0            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir0);
HI_VOID VDP_VID_SetMediffcntminnorthrdir0           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir0);
HI_VOID VDP_VID_SetMediff3thrdir1                   (HI_U32 u32Data, HI_U32 mediff3thrdir1);
HI_VOID VDP_VID_SetMediffcntmintenthrdir1           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir1);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir1            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir1);
HI_VOID VDP_VID_SetMediffcntminnorthrdir1           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir1);
HI_VOID VDP_VID_SetMediff3thrdir2                   (HI_U32 u32Data, HI_U32 mediff3thrdir2);
HI_VOID VDP_VID_SetMediffcntmintenthrdir2           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir2);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir2            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir2);
HI_VOID VDP_VID_SetMediffcntminnorthrdir2           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir2);
HI_VOID VDP_VID_SetMediff3thrdir3                   (HI_U32 u32Data, HI_U32 mediff3thrdir3);
HI_VOID VDP_VID_SetMediffcntmintenthrdir3           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir3);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir3            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir3);
HI_VOID VDP_VID_SetMediffcntminnorthrdir3           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir3);
HI_VOID VDP_VID_SetMediff3thrdir4                   (HI_U32 u32Data, HI_U32 mediff3thrdir4);
HI_VOID VDP_VID_SetMediffcntmintenthrdir4           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir4);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir4            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir4);
HI_VOID VDP_VID_SetMediffcntminnorthrdir4           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir4);
HI_VOID VDP_VID_SetMediff3thrdir5                   (HI_U32 u32Data, HI_U32 mediff3thrdir5);
HI_VOID VDP_VID_SetMediffcntmintenthrdir5           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir5);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir5            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir5);
HI_VOID VDP_VID_SetMediffcntminnorthrdir5           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir5);
HI_VOID VDP_VID_SetMediff3thrdir6                   (HI_U32 u32Data, HI_U32 mediff3thrdir6);
HI_VOID VDP_VID_SetMediffcntmintenthrdir6           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir6);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir6            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir6);
HI_VOID VDP_VID_SetMediffcntminnorthrdir6           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir6);
HI_VOID VDP_VID_SetMediff3thrdir7                   (HI_U32 u32Data, HI_U32 mediff3thrdir7);
HI_VOID VDP_VID_SetMediffcntmintenthrdir7           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir7);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir7            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir7);
HI_VOID VDP_VID_SetMediffcntminnorthrdir7           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir7);
HI_VOID VDP_VID_SetDemomodecoor                     (HI_U32 u32Data, HI_U32 demomodecoor);
HI_VOID VDP_VID_SetSnrMotionEdgeLut                 (HI_U32 u32Data, HI_U32 snrmotionedgelut[16][32]);
HI_VOID VPSS_DRV_SetSnrColorBasedLut                (HI_U32 u32Data, HI_U32 snrcbcrlut[16][16]);
#endif
