
obj-y	+= nand_sync.o nand_sync_onfi.o nand_sync_toggle.o
obj-$(CONFIG_ARCH_HI3798MV2X)	+= nand_sync_hi3798mv2x.o
obj-$(CONFIG_ARCH_HI3798MV310)	+= nand_sync_hi3798mv310.o
obj-$(CONFIG_ARCH_HI3796MV2X)	+= nand_sync_hi3796mv2x.o
obj-$(CONFIG_ARCH_S40)	+= nand_sync_others.o
obj-$(CONFIG_ARCH_HI3798CV2X)	+= nand_sync_others.o
obj-$(CONFIG_ARCH_HI3716MV420N)	+= nand_sync_others.o

ccflags-y += -I./drivers/mtd/hisilicon
