LOCAL_C_INCLUDES := \
	-I$(HI_TEE_DRV_DIR)/mem/sec_mmz/include \
    -I$(HI_TEE_API_DIR)/klad
	
LOCAL_SRC_FILES := \
         hisi_klad_task.o

LOCAL_MODULE:= $(OUT)/task_hisi_klad.elf

include $(HI_TEE_TA_DIR)/ta.mak
