LOCAL_C_INCLUDES := \
    -I$(HI_TEE_API_DIR)/mem/include \
    -I$(HI_TEE_API_DIR)/hdmi

LOCAL_SRC_FILES := \
	task_sec_hdmi.o

LOCAL_MODULE:= $(OUT)/task_sec_hdmi.elf

include $(HI_TEE_TA_DIR)/ta.mak
